---
- name: Install required system packages
  ansible.builtin.apt:
    name:
      - snapd
    state: present

- name: Install microk8s via snap
  community.general.snap:
    name: microk8s
    classic: true
    channel: stable

- name: Create microk8s group
  ansible.builtin.group:
    name: microk8s
    state: present

- name: Add current user to microk8s group
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups:
      - microk8s
    append: true

- name: Add user to microk8s group
  ansible.builtin.user:
    name: "{{ username }}"
    groups:
      - microk8s
    append: true

- name: Start microk8s
  ansible.builtin.command: microk8s start --wait-ready

- name: Enable microk8s addons
  ansible.builtin.command: "microk8s enable {{ item }}"
  loop:
    - community
    - ingress
    - dns
    - storage
    - cert-manager
    - helm
  register: microk8s_addons
  changed_when: microk8s_addons.rc == 0
# - name: Restart microk8s
#   ansible.builtin.command: microk8s stop && microk8s start
#   when: microk8s_addons.changed
