#!/bin/bash
extra_args="${*:2}"

set -e
kubectl create namespace "$1" || true

# shellcheck disable=SC2086
jsonnet -J ./k8s/vendor -y $extra_args "k8s/$1.jsonnet" | yq -P >"k8s/dist/$1.yaml" && kubectl apply -n "$1" -f "k8s/dist/$1.yaml"
