---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: music-vol-claim
  namespace: navidrome
spec:
  accessModes: ["ReadOnlyMany"]
  selector:
    matchLabels:
      storageName: music
  resources:
    requests:
      storage: 1Ti
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: navidrome-vol-claim
  namespace: navidrome
spec:
  accessModes: ["ReadWriteOnce"]
  selector:
    matchLabels:
      storageName: navidrome
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: navidrome
  namespace: navidrome
  labels:
    app.kubernetes.io/name: navidrome
spec:
  containers:
    - name: navidrome
      image: deluan/navidrome
      imagePullPolicy: Always
      ports:
        - name: web
          containerPort: 4533
      env:
        - name: ND_SCANSCHEDULE
          value: 1h
        - name: ND_LOGLEVEL
          value: info
        - name: ND_SESSIONTIMEOUT
          value: 24h
        - name: ND_ENABLESHARING
          value: "true"
        - name: ND_BASEURL
          value: ""
      resources:
        limits:
          memory: 4Gi
          cpu: "4"
      volumeMounts:
        - name: music-vol
          mountPath: /music
        - name: navidrome-vol
          mountPath: /data
  volumes:
    - name: navidrome-vol
      persistentVolumeClaim:
        claimName: navidrome-vol-claim
    - name: music-vol
      persistentVolumeClaim:
        claimName: music-vol-claim
---
apiVersion: v1
kind: Service
metadata:
  namespace: navidrome
  name: navidrome-service
spec:
  selector:
    app.kubernetes.io/name: navidrome
  ports:
    - name: web
      protocol: TCP
      port: 4533
      targetPort: 4333
