- name: "Copy helm charts to host"
  ansible.builtin.copy:
    src: "../charts"
    dest: "/var/lib/helm"
    force: true
    mode: "0644"

- name: "Ensure Helm charts are deployed"
  kubernetes.core.helm:
    name: "{{ item }}"
    binary_path: /snap/bin/microk8s.helm
    chart_ref: "/var/lib/helm/charts"
    values_files:
      - "/var/lib/helm/charts/values/{{ item }}.yaml"
    create_namespace: true
    release_namespace: "{{ item }}"
    release_state: present
  with_items: "{{ helm_configs }}"
