- name: "Create remote charts directory"
  ansible.builtin.file:
    path: "{{ helm.charts_dir }}"
    state: directory
    mode: "0755"

- name: "Synchronize charts to remote server"
  synchronize:
    src: "{{ helm.local_chart_dir }}"
    dest: "{{ helm.charts_dir }}"
    delete: true
    recursive: true

- name: "Ensure Helm charts are deployed"
  kubernetes.core.helm:
    name: "{{ item.name }}"
    binary_path: /snap/bin/microk8s.helm
    chart_ref: "{{ helm.charts_dir }}/{{ item.kind }}"
    values_files:
      - "{{ helm.charts_dir }}/{{ item.values }}"
    create_namespace: true
    release_namespace: "{{ item.name }}"
    release_state: present
  with_items: "{{ helm_configs }}"
