name: jaritanet
description: Personal infra
runtime:
  name: nodejs
  options:
    # Disable built-in TypeScript support
    typescript: false
    # Manually set arguments for the Node interpreter to use a custom loader
    nodeargs: "--import tsx/esm"
config:
  pulumi:tags:
    value:
      pulumi:template: typescript
