# yaml-language-server: $schema=../../schemas/infra.json
config:
  cloudflare:apiToken:
    secure: AAABAJee5AsdP//8cTEkQfjB8ofZqj5ftTaGkdLMz2XjDhXOQmcQJ1GWKPB9a43CSoHRN5292UuGCfvLQmnyFHHkTP5AwYLd
  jaritanet:cloudflare:
    accountId: ''
  jaritanet:tunnel:
    name: "jaritanet"
