samba_shares:
  - name: music
    path: "/mnt/kontent/music"
    write_list: jc
  - name: movies
    path: "/mnt/kontent/movies"
    write_list: jc
  - name: tv
    path: "/mnt/kontent/tv"
    write_list: jc
  - name: files
    path: "/srv/files"
    write_list: jc

tailscale_routes:
  - 192.168.50.0/24

helm_configs:
  - name: navidrome
    kind: local-server
    values: local-server/values/navidrome.yaml
  - name: files
    kind: local-server
    values: local-server/values/files.yaml
  # - name: cf-tunnel
  #   type: cf-tunnel
  #   values: cf-tunnel/values.yaml
  #   set_values:
  #     - value: token="{{ lookup('env', 'TUNNEL_TOKEN') }}"
