image:
  repository: alpine/git
  tag: latest
  pullPolicy: IfNotPresent

schedule: "* * * * *" # Run hourly by default

gitConfig:
  email: "automation@radiosilence.dev"
  name: "IP Update Automation"

# Configure your git repository
gitRepo:
  url: "git@github.com:radiosilence/jaritanet.git"
  branch: "main"
