apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.statefulset.name }}
  namespace: {{ .Values.global.namespace }}
spec:
  serviceName: {{ .Values.service.name }}
  replicas: {{ .Values.statefulset.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.statefulset.name }}
  template:
    metadata:
      namespace: {{ .Values.global.namespace }}
      labels:
        app: {{ .Values.statefulset.name }}
    spec:
      containers:
        - name: {{ .Values.statefulset.name }}
          image: {{ .Values.statefulset.image.repository }}:{{ .Values.statefulset.image.tag }}
          imagePullPolicy: {{ .Values.statefulset.image.pullPolicy }}
          ports:
            {{- range $key, $port := .Values.statefulset.ports }}
            - name: {{ $key }}
              containerPort: {{ $port }}
            {{- end }}
          {{- if .Values.statefulset.environment }}
          env:
            {{- range $key, $value := (.Values.statefulset.environment | default "{}") }}
            - name: {{ $key }}
              value: "{{ $value }}"
            {{- end }}
          {{- end }}
          resources:
            limits:
              memory: {{ .Values.statefulset.resources.limits.memory }}
              cpu: {{ .Values.statefulset.resources.limits.cpu }}
          volumeMounts:
{{- range $key, $volume := .Values.persistence }}
            - name: {{ $key }}-vol-claim
              mountPath: {{ $volume.mountPath }}
{{- end }}
  volumeClaimTemplates:
{{- range $key, $volume := .Values.persistence }}
    - metadata:
        name: {{ $key }}-vol-claim
        namespace: {{ $.Values.global.namespace }}
      spec:
        accessModes: ["{{ $volume.accessMode }}"]
        storageClassName: {{ $volume.storageClass }}
        selector:
          matchLabels:
            storageName: {{ $key }}
        resources:
          requests:
            storage: {{ $volume.storageSize }}
{{- end }}
