global:
  namespace: files

persistence:
  storageClass: local-storage
  storageSize: 10Gi
  claimStorageSize: 5Gi
  local:
    path: /srv/files

statefulset:
  replicas: 1
  image:
    repository: ghcr.io/radiosilence/jaritanet-files
    tag: latest
    pullPolicy: Always
  resources:
    limits:
      memory: 4Gi
      cpu: "2"
  nodeSelector:
    key: kubernetes.io/hostname
    operator: In
    values:
      - oldboy

service:
  name: files-service
  port: 80

ingress:
  enabled: true
  host: files.radiosilence.dev
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
