# yaml-language-server: $schema=../../schemas/k8s.json
config:
  jaritanet-k8s:cloudflare:
    accountId: ''
  jaritanet-k8s:services:
    navidrome:
      hostname: ''
      proxied: true
      args:
        httpPort: 4533
        strategy:
          type: Recreate
        image:
          repository: "deluan/navidrome"
          tag: 0.58.0
          pullPolicy: "Always"
        env:
          ND_SCANSCHEDULE: 1h
          ND_LOGLEVEL: info
          ND_SESSIONTIMEOUT: 24h
          ND_ENABLESHARING: "true"
          ND_ENABLETRANSCODINGCONFIG: "true"
          ND_TRANSCODINGCACHESIZE: 5Gi
          ND_ENABLEGRAVATAR: "true"
        healthCheck:
          path: "/ping"
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
        limits:
          cpu: 2000m
          memory: 8Gi
        nodeSelector:
          key: kubernetes.io/hostname
          operator: In
          values:
            - oldboy
        persistence:
          - name: music
            storage: 2Ti
            hostPath: /mnt/kontent/music
            mountPath: /music
            readOnly: true
            nodeAffinityHostname: oldboy
          - name: data
            storage: 20Gi
            hostPath: /home/navidrome/data
            mountPath: /data
            readOnly: false
            nodeAffinityHostname: oldboy
    files:
      hostname: ''
      args:
        strategy:
          type: Recreate
        image:
          repository: "ghcr.io/radiosilence/jaritanet-files"
          tag: latest
          pullPolicy: "Always"
        replicas: 1
        nodeSelector:
          key: kubernetes.io/hostname
          operator: In
          values:
            - oldboy
        persistence:
          - name: files
            storage: 20Mi
            hostPath: /srv/files
            mountPath: /srv/files
            nodeAffinityHostname: oldboy
    blit:
      hostname: ''
      args:
        replicas: 2
        healthCheck: {}
        limits:
          cpu: 1000m
          memory: 1024Mi
        image:
          repository: "ghcr.io/radiosilence/blit"
          tag: sha-4b1388c
          pullPolicy: "Always"
        httpPort: 3000
    dotfiles:
      args:
        replicas: 1
        strategy:
          type: Recreate
        healthCheck:
          path: "/"
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
        limits:
          cpu: 500m
          memory: 512Mi
        image:
          repository: "ghcr.io/radiosilence/dotfiles"
          tag: latest
          pullPolicy: "Always"
        nodeSelector:
          key: kubernetes.io/hostname
          operator: In
          values:
            - oldboy
        persistence:
          - name: kontent
            storage: 4Ti
            hostPath: /mnt/kontent
            mountPath: /mnt/kontent
            readOnly: false
            nodeAffinityHostname: oldboy
  jaritanet-k8s:cloudflared:
    name: cloudflared
    args:
      replicas: 2
  cloudflare:apiToken:
    secure: AAABAO3Q5Z9RUZgleETmCvoaMOr3oPcs19Qc/Cp6C8pfb1EaBASR4AUQkqfoYaTI1NN+GiQJFQlbsBhGlNaP6DBdUi4ny5zR
