config:
  jaritanet-k8s:cloudflare:
    accountId: 365e5168438376dc99d7ee2aedef4624
  jaritanet-k8s:services:
    - name: navidrome
      hostname: music.blit.cc
      proxied: true
      args:
        httpPort: 4533
        strategy:
          type: Recreate
        image:
          repository: "deluan/navidrome"
          tag: 0.55.0
          pullPolicy: "Always"
        env:
          ND_SCANSCHEDULE: 1h
          ND_LOGLEVEL: info
          ND_SESSIONTIMEOUT: 24h
          ND_ENABLESHARING: "true"
          ND_ENABLETRANSCODINGCONFIG: "true"
          ND_TRANSCODINGCACHESIZE: 5Gi
          ND_ENABLEGRAVATAR: "true"
        healthCheck:
          path: "/"
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
        limits:
          cpu: 2000m
          memory: 8Gi
        nodeSelector:
          key: kubernetes.io/hostname
          operator: In
          values:
            - oldboy
        persistence:
          - name: music
            storage: 2Ti
            hostPath: /mnt/kontent/music
            mountPath: /music
            nodeAffinityHostname: oldboy
          - name: data
            storage: 20Gi
            hostPath: /home/navidrome/data
            mountPath: /data
            readOnly: false
            nodeAffinityHostname: oldboy
    - name: files
      hostname: files.radiosilence.dev
      args:
        strategy:
          type: Recreate
        image:
          repository: "ghcr.io/radiosilence/jaritanet-files"
          tag: latest
          pullPolicy: "Always"
        replicas: 1
        nodeSelector:
          key: kubernetes.io/hostname
          operator: In
          values:
            - oldboy
        persistence:
          - name: files
            storage: 20Mi
            hostPath: /srv/files
            mountPath: /srv/files
            nodeAffinityHostname: oldboy
    - name: blit
      hostname: blit.cc
      args:
        replicas: 2
        healthCheck: {}
        image:
          repository: "ghcr.io/radiosilence/blit"
          tag: sha-a72fc80
          pullPolicy: "Always"
        httpPort: 3000
  jaritanet-k8s:cloudflared:
    name: cloudflared
    args:
      replicas: 2
  cloudflare:apiToken:
    secure: AAABAMqg9u/8sqfZC9qSCmJwf5Rb1Px2EfzFnpRkI3uAI872vNEJE9q8XgKqcbkD+vQn/s0fwwyS02NnGMoatRNOpzxURXeP
