config:
  jaritanet-k8s:services:
    - name: navidrome
      hostname: music.blit.cc
      args:
        httpPort: 4533
        image:
          repository: "deluan/navidrome"
          tag: latest
          pullPolicy: "Always"
        env:
          ND_SCANSCHEDULE: "1h"
          ND_LOGLEVEL: "info"
          ND_SESSIONTIMEOUT: "24h"
          ND_ENABLESHARING: "true"
          ND_ENABLETRANSCODINGCONFIG: "true"
        limits:
          cpu: 2000m
          memory: 2Gi
        nodeSelector:
          key: kubernetes.io/hostname
          operator: In
          values:
            - oldboy
        hostVolumes:
          - name: music
            hostPath: /mnt/kontent/music
            mountPath: /music
          - name: data
            hostPath: /home/navidrome/data
            mountPath: /data
            readOnly: false
    - name: files
      hostname: files.radiosilence.dev
      args:
        image:
          repository: "ghcr.io/radiosilence/jaritanet-files"
          tag: latest
          pullPolicy: "Always"
        nodeSelector:
          key: kubernetes.io/hostname
          operator: In
          values:
            - oldboy
        persistence:
          - name: files
            storage: 20Mi
            hostPath: /srv/files
            mountPath: /srv/files
            nodeAffinityHostname: oldboy

    - name: blit
      hostname: blit.cc
      args:
        replicas: 2
        limits:
          cpu: 250m
          memory: 256Mi
        image:
          repository: "ghcr.io/radiosilence/blit"
          tag: latest
          pullPolicy: "Always"

    # - name: bambi-art
    #   hostname: bambi.radiosilence.dev
    #   template: web
    #   args:
    #     httpPort: 3000
    #     image:
    #       repository: "ghcr.io/radiosilence/bambi-art"
    #       tag: latest
    #       pullPolicy: "Always"

  jaritanet-k8s:cloudflared:
    name: cloudflared
