config:
  jaritanet-k8s:services:
    - name: navidrome
      hostname: music.blit.cc
      template: local-storage
      args:
        httpPort: 4533
        image:
          repository: "deluan/navidrome"
          tag: latest
          pullPolicy: "Always"
        env:
          ND_SCANSCHEDULE: "1h"
          ND_LOGLEVEL: "info"
          ND_SESSIONTIMEOUT: "24h"
          ND_ENABLESHARING: "true"
          ND_ENABLETRANSCODINGCONFIG: "true"
        resources:
          limits:
            cpu: 2000m
            memory: 2Gi
        nodeSelector:
          key: kubernetes.io/hostname
          operator: In
          values:
            - oldboy
        hostVolumes:
          - name: music
            hostPath: /mnt/kontent/music
            mountPath: /music
          - name: data
            hostPath: /home/navidrome/data
            mountPath: /data
            rw: true
    - name: files
      hostname: files.radiosilence.dev
      template: local-storage
      args:
        image:
          repository: "ghcr.io/radiosilence/jaritanet-files"
          tag: latest
          pullPolicy: "Always"
        resources:
          limits:
            cpu: 50m
            memory: 64Mi
        nodeSelector:
          key: kubernetes.io/hostname
          operator: In
          values:
            - oldboy
        hostVolumes:
          - name: files
            hostPath: /srv/files
            mountPath: /srv/files

    - name: blit
      hostname: blit.cc
      template: static
      args:
        image:
          repository: "ghcr.io/radiosilence/blit"
          tag: latest
          pullPolicy: "Always"

    - name: bambi-art
      hostname: bambi.radiosilence.dev
      template: static
      args:
        httpPort: 3000
        image:
          repository: "ghcr.io/radiosilence/bambi-art"
          tag: latest
          pullPolicy: "Always"

  jaritanet-k8s:cloudflared:
    name: cloudflared
