---
- name: update grub
  ansible.builtin.command: update-grub
  changed_when: true
  listen: update grub

- name: restart sshd
  ansible.builtin.systemd:
    name: ssh
    state: restarted
    daemon_reload: true
  listen: restart sshd