apiVersion: v2
name: jaritanet
description: A Helm chart collection for deploying various stateful applications
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: navidrome
    version: 0.1.0
    condition: navidrome.enabled
  - name: files
    version: 0.1.0
    condition: files.enabled
