---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blursed-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blursed-app
  template:
    metadata:
      labels:
        app: blursed-app
    spec:
      volumes:
        - name: blursed-vol
          persistentVolumeClaim:
            claimName: blursed-pvc
      containers:
        - name: blursed-container
          image: nginx:mainline-alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: blursed-vol
              mountPath: /usr/share/nginx/html
          resources:
            limits:
              cpu: 25m
              memory: 32Mi
