- name: Download Speedtest CLI GPG key
  ansible.builtin.get_url:
    url: https://packagecloud.io/ookla/speedtest-cli/gpgkey
    dest: /etc/apt/keyrings/ookla_speedtest-cli-archive-keyring.gpg
    mode: '0644'
    owner: root
    group: root

- name: Add Speedtest CLI repo using key from URL
  ansible.builtin.deb822_repository:
    name: ookla_speedtest-cli
    types: [deb, deb-src]
    uris: https://packagecloud.io/ookla/speedtest-cli/ubuntu/
    components: [main]
    suites: ["{{ ansible_distribution_release }}"]
    signed_by: /etc/apt/keyrings/ookla_speedtest-cli-archive-keyring.gpg
    state: present
    enabled: true

- name: Install Speedtest CLI
  ansible.builtin.apt:
    name: speedtest
    state: present
    update_cache: true