name: Publish Files Container

permissions:
  contents: read
  packages: write

on:
  push:
    branches:
      - main
    tags:
      - v*
    paths:
      - "containers/files/**"
      - ".github/workflows/build-files-container.yml"
  pull_request:

jobs:
  publish:
    uses: radiosilence/blit-workflows/.github/workflows/build-publish-container.yml@main
    with:
      working_directory: "./containers/files"
      image: "files"
    secrets:
      PASSWORD: ${{ secrets.GITHUB_TOKEN }}
