name: Pulumi Infra

permissions:
  contents: read

on:
  workflow_call:
    secrets:
      PULUMI_ACCESS_TOKEN:
        required: true

concurrency:
  group: "infra"

jobs:
  up:
    name: Update
    runs-on: ubuntu-24.04
    env:
      working-directory: ./infra
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
      - run: bun install
      - uses: pulumi/actions@v6
        with:
          command: up
          stack-name: radiosilence/jaritanet/main
          work-dir: infra
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
