name: Pulumi k8s

permissions:
  contents: read

on:
  workflow_call:
    inputs:
      stack-name:
        type: string
        required: true
      working-directory:
        type: string
        required: true
    secrets:
      PULUMI_ACCESS_TOKEN:
        required: true
      TS_OAUTH_CLIENT_ID:
        required: true
      TS_OAUTH_SECRET:
        required: true
      KUBE_HOST:
        required: true
      KUBE_API_PORT:
        required: true
      KUBE_TOKEN:
        required: true

concurrency:
  group: "k8s"

env:
  KUBECONFIG: ${{ github.workspace }}/kubeconfig.yaml

jobs:
  up:
    name: Update
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Tailscale
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci
      - name: Generate kubeconfig
        run: |
          cat << EOF > ${{ env.KUBECONFIG }}
          apiVersion: v1
          kind: Config
          clusters:
          - cluster:
              server: https://${{ secrets.KUBE_HOST }}:${{ secrets.KUBE_API_PORT }} 
              insecure-skip-tls-verify: true  # Only if you're using self-signed certs
            name: microk8s-cluster
          contexts:
          - context:
              cluster: microk8s-cluster
              user: admin
            name: microk8s
          current-context: microk8s
          users:
          - name: admin
            user:
              token: ${{ secrets.KUBE_TOKEN }}  # Get this from your microk8s cluster
          EOF
      - uses: pnpm/action-setup@v4
        with:
          version: latest
          package_json_file: ${{ inputs.working-directory }}/package.json
          run_install: true
      - uses: pulumi/actions@v6
        with:
          command: up
          stack-name: ${{ inputs.stack-name }}
          work-dir: ${{ inputs.working-directory }}
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          KUBECONFIG: ${{ github.workspace }}/kubeconfig.yaml
