name: Pulumi Infra

permissions:
  contents: read

on:
  workflow_call:
    secrets:
      PULUMI_ACCESS_TOKEN:
        required: true

concurrency:
  group: "infra"

jobs:
  up:
    name: Update
    runs-on: ubuntu-24.04
    env:
      working-directory: ./infra
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: latest
          package_json_file: ${{env.working-directory}}/package.json
          run_install: true
      - uses: pulumi/actions@v6
        with:
          command: up
          stack-name: radiosilence/jaritanet/main
          work-dir: ${{env.working-directory}}/
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
