name: k8s -> routes

permissions:
  contents: read

on:
  push:
    branches:
      - main
    paths:
      - "k8s/**"
      - ".github/workflows/*-k8s.yml"
  workflow_call:
    secrets:
      PULUMI_ACCESS_TOKEN:
        required: true
      TS_OAUTH_CLIENT_ID:
        required: true
      TS_OAUTH_SECRET:
        required: true
      KUBE_HOST:
        required: true
      KUBE_API_PORT:
        required: true
      KUBE_TOKEN:
        required: true

env:
  KUBECONFIG: ${{ github.workspace }}/kubeconfig.yaml

concurrency:
  group: "k8s"

jobs:
  k8s:
    name: K8s
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Tailscale
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci
      - uses: jdx/mise-action@v2
      - run: bun install
      - uses: pulumi/actions@v6
        with:
          command: up
          stack-name: radiosilence/jaritanet-k8s/main
          work-dir: k8s
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          KUBECONFIG: ${{ github.workspace }}/kubeconfig.yaml
          KUBE_HOST: ${{ secrets.KUBE_HOST }}
          KUBE_API_PORT: ${{ secrets.KUBE_API_PORT }}
          KUBE_TOKEN: ${{ secrets.KUBE_TOKEN }}

  routes:
    name: Routes
    needs: k8s
    uses: ./.github/workflows/update-routes.yml
    secrets:
      PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
