name: 🛣️ Routes

permissions:
  contents: read

on:
  push:
    branches:
      - main
    paths:
      - "packages/routes/**"
      - ".github/workflows/*-routes.yml"
  workflow_call:
    secrets:
      PULUMI_ACCESS_TOKEN:
        required: true

concurrency:
  group: "routes"

jobs:
  routes:
    name: 🛣️ Deploy Routes
    runs-on: ubuntu-24.04
    env:
      working-directory: ./packages/routes
    steps:
      - name: 📥 Checkout Repository
        uses: actions/checkout@v4
      - name: 🛠️ Setup Development Environment
        uses: jdx/mise-action@v2
      - name: 📦 Install Dependencies
        run: bun install
      - name: 🚀 Deploy with Pulumi
        uses: pulumi/actions@v6
        with:
          command: up
          stack-name: radiosilence/jaritanet-routes/main
          work-dir: packages/routes
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
