name: Update Infra

permissions:
  contents: read

on:
  push:
    branches:
      - main
    paths:
      - "routes/**"
      - "infra/**"
      - "k8s/**"
      - ".github/workflows/update-infra.yml"
      - ".github/workflows/pulumi-*.yml"

jobs:
  infra:
    name: Infra
    uses: ./.github/workflows/pulumi-infra.yml
    with:
      stack-name: radiosilence/jaritanet/main
      working-directory: ./infra
    secrets:
      PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
  k8s:
    name: K8s
    needs: infra
    uses: ./.github/workflows/pulumi-k8s.yml
    with:
      stack-name: radiosilence/jaritanet-k8s/main
      working-directory: ./k8s
    secrets:
      PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
      TS_OAUTH_CLIENT_ID: ${{ secrets.TS_OAUTH_CLIENT_ID }}
      TS_OAUTH_SECRET: ${{ secrets.TS_OAUTH_SECRET }}
      KUBE_HOST: ${{ secrets.KUBE_HOST }}
      KUBE_API_PORT: ${{ secrets.KUBE_API_PORT }}
      KUBE_TOKEN: ${{ secrets.KUBE_TOKEN }}
  routes:
    name: Routes
    needs: k8s
    uses: ./.github/workflows/pulumi-routes.yml
    with:
      stack-name: radiosilence/jaritanet-routes/main
      working-directory: ./routes
    secrets:
      PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
