name: Update Infra

permissions:
  contents: read

on:
  push:
    branches:
      - main
    paths:
      - "routes/**"
      - "infra/**"
      - "k8s/**"
      - ".github/workflows/update-infra.yml"
      - ".github/workflows/pulumi-*.yml"

jobs:
  infra:
    name: Update Infra
    uses: ./.github/workflows/pulumi-infra.yml
  k8s:
    name: Update K8s
    needs: infra
    uses: ./.github/workflows/pulumi-k8s.yml
    with:
      stack-name: radiosilence/jaritanet/main
      working-directory: ./k8s
  routes:
    name: Update Routes
    needs: k8s
    uses: ./.github/workflows/pulumi-routes.yml
