apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-scripts
data:
  update-ip.sh: |
    #!/bin/bash
    
    set -e

    # Configure git
    git config --global user.email "{{ .Values.gitConfig.email }}"
    git config --global user.name "{{ .Values.gitConfig.name }}"

    echo "Configuring git..."

    # Clone the repository
    echo "Cloning repository..."
    git clone {{ .Values.gitRepo.url }} /workspace
    cd /workspace

    # Checkout the specified branch
    echo "Checking out branch {{ .Values.gitRepo.branch }}..."
    git checkout {{ .Values.gitRepo.branch }}
    
    VARS_FILE=./terraform/vars-ip.tf.json

    # Get the current IP address from the vars.tf file
    echo "Getting current IP address..."
    CURRENT_IP=$(jq -r '.variable.jaritanet_ip.default' $VARS_FILE)

    echo "Current IP address is $CURRENT_IP"

    # Get the latest IP address (replace with your actual IP retrieval logic)
    echo "Getting new IP address..."
    NEW_IP=$(curl jsonip.com | jq -r .ip)
    echo "New IP address is $NEW_IP"

    # Check if the IP has changed
    if [ "$CURRENT_IP" != "$NEW_IP" ]; then
        echo "IP has changed from $CURRENT_IP to $NEW_IP"
        
        # Update the vars.tf file
        jq --arg new_ip "$NEW_IP" '.variable.jaritanet_ip.default = $new_ip' "$VARS_FILE" > /tmp/vars
        mv /tmp/vars "$VARS_FILE"

        # Stage and commit the changes
        git add "$VARS_FILE"
        git commit -m "chore: Update JARITANET IP to $NEW_IP"
        
        # Push the changes
        git push origin {{ .Values.gitRepo.branch }}
        
        echo "Successfully updated IP and pushed changes"
    else
        echo "IP hasn't changed, no update needed"
    fi