apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-cronjob
spec:
  schedule: {{ .Values.schedule | quote }}
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 5
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      # backoffLimit: 3
      ttlSecondsAfterFinished: 86400 
      template:
        spec:
          containers:
          - name: ip-updater
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            volumeMounts:
            - name: ssh
              mountPath: /root/.ssh
              readOnly: true
            - name: scripts
              mountPath: /scripts
            command:
            - /bin/sh
            - -c
            - |
              apk add bash curl jq 
              /scripts/update-ip.sh

          volumes:
          - name: scripts
            configMap:
              name: {{ .Release.Name }}-scripts
              defaultMode: 0755
          - name: ssh
            secret:
              secretName: {{ .Release.Name }}-ssh
              defaultMode: 0400
          restartPolicy: OnFailure
