# templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-ssh
type: Opaque
stringData:
  id_ed25519: {{ .Values.sshKey | quote }}
  known_hosts: {{ .Values.knownHosts | quote }}